<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { ref } from 'vue';
import PageHeader from '@/Components/Shared/PageHeader.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const props=defineProps<{invoices:any[];filters:any}>(); const search=ref(props.filters.search??''); const status=ref(props.filters.status??'');
const apply=()=>router.get('/admin/advertising-invoices',{search:search.value,status:status.value},{preserveState:true});
const money=(v:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(v/100);
</script>
<template><Head title="Advertising Billing"/><div class="space-y-6 p-6"><div class="flex items-start justify-between gap-4"><PageHeader title="Advertising Billing" description="Manage advertiser invoices, balances, payments, and refunds."/><Link href="/admin/advertising-invoices/create"><Button>Create Invoice</Button></Link></div><div class="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_220px_auto]"><Input v-model="search" placeholder="Search invoice or advertiser"/><select v-model="status" class="h-10 rounded-md border bg-background px-3"><option value="">All statuses</option><option v-for="x in ['draft','issued','partially_paid','paid','overdue','void','refunded']" :value="x">{{x.replace('_',' ')}}</option></select><Button @click="apply">Apply</Button></div><div class="overflow-x-auto rounded-xl border"><table class="w-full text-sm"><thead class="bg-muted/40 text-left"><tr><th class="p-3">Invoice</th><th class="p-3">Advertiser</th><th class="p-3">Campaign</th><th class="p-3">Status</th><th class="p-3 text-right">Total</th><th class="p-3 text-right">Balance</th><th class="p-3">Due</th></tr></thead><tbody><tr v-for="x in invoices" :key="x.id" class="border-t"><td class="p-3"><Link :href="`/admin/advertising-invoices/${x.id}`" class="font-medium underline">{{x.invoice_number}}</Link></td><td class="p-3">{{x.advertiser?.name}}</td><td class="p-3">{{x.campaign?.name||'—'}}</td><td class="p-3 capitalize">{{x.status.replace('_',' ')}}</td><td class="p-3 text-right">{{money(x.total_cents,x.currency)}}</td><td class="p-3 text-right font-medium">{{money(x.balance_cents,x.currency)}}</td><td class="p-3">{{x.due_at||'—'}}</td></tr><tr v-if="!invoices.length"><td colspan="7" class="p-10 text-center text-muted-foreground">No advertising invoices match the current filters.</td></tr></tbody></table></div></div></template>
