<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'; import { ImageIcon, Pencil, Trash2, Upload } from '@lucide/vue'; import ImageEditorDialog,{type ImageEditData} from '@/components/media/ImageEditorDialog.vue'; import { PUBLIC_PAGE_HEADER_PRESET } from '@/config/imageEditorPresets'; import { Button } from '@/components/ui/button';
const props=withDefaults(defineProps<{initialImageUrl?:string|null;initialOriginalUrl?:string|null;initialEditData?:ImageEditData|null;error?:string|null}>(),{initialImageUrl:null,initialOriginalUrl:null,initialEditData:null,error:null});
const emit=defineEmits<{apply:[payload:{original:File|null;rendered:File;edit:ImageEditData}];remove:[]}>(); const editorOpen=ref(false), selectedOriginal=ref<File|null>(null), source=ref<File|string|null>(props.initialOriginalUrl??props.initialImageUrl), previewUrl=ref<string|null>(props.initialImageUrl), editData=ref<ImageEditData|null>(props.initialEditData), removed=ref(false), inputKey=ref(0); const hasImage=computed(()=>Boolean(previewUrl.value)&&!removed.value);
function choose(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;selectedOriginal.value=f;source.value=f;removed.value=false;editorOpen.value=true;}
function apply(p:{file:File;edit:ImageEditData;previewUrl:string}){if(previewUrl.value?.startsWith('blob:'))URL.revokeObjectURL(previewUrl.value);previewUrl.value=p.previewUrl;editData.value=p.edit;removed.value=false;emit('apply',{original:selectedOriginal.value,rendered:new File([p.file],p.file.name||'page-header.jpg',{type:p.file.type||'image/jpeg'}),edit:p.edit});}
function remove(){if(previewUrl.value?.startsWith('blob:'))URL.revokeObjectURL(previewUrl.value);previewUrl.value=null;source.value=null;selectedOriginal.value=null;editData.value=null;removed.value=true;inputKey.value++;emit('remove');}
onBeforeUnmount(()=>{if(previewUrl.value?.startsWith('blob:'))URL.revokeObjectURL(previewUrl.value)});
</script>
<template><ImageEditorDialog v-model:open="editorOpen" :source="source" filename="public-page-header.jpg" :preset="PUBLIC_PAGE_HEADER_PRESET" :initial-edit="editData" @apply="apply"/><div class="space-y-4"><div v-if="hasImage" class="overflow-hidden rounded-xl border bg-muted"><img :src="previewUrl??''" alt="Public page header preview" class="aspect-[16/7] w-full object-cover"/><div class="flex flex-wrap items-center justify-between gap-3 p-3"><span class="flex items-center gap-2 text-sm text-muted-foreground"><ImageIcon class="h-4 w-4"/>1600 × 700</span><div class="flex gap-2"><Button type="button" size="sm" variant="outline" @click="editorOpen=true"><Pencil class="mr-2 h-4 w-4"/>Edit crop</Button><Button type="button" size="sm" variant="outline" @click="remove"><Trash2 class="mr-2 h-4 w-4"/>Remove</Button></div></div></div><label class="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-6 text-sm font-medium hover:bg-muted/40"><Upload class="h-4 w-4"/>{{hasImage?'Replace header image':'Choose header image'}}<input :key="inputKey" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="choose"/></label><p class="text-sm text-muted-foreground">The original is retained; the edited 1600 × 700 image is shown in the public page hero.</p><p v-if="error" class="text-sm text-destructive">{{error}}</p></div></template>
