<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import { AlertTriangle, BadgeDollarSign, Clock3, PackageCheck } from '@lucide/vue';
import AnalyticsEmptyState from '@/components/Analytics/AnalyticsEmptyState.vue';
import AnalyticsHeader from '@/components/Analytics/AnalyticsHeader.vue';
import MetricCard from '@/Components/Shared/MetricCard.vue';
import ShowSection from '@/Components/Show/ShowSection.vue';
import { Button } from '@/components/ui/button';
defineProps<{ filters:any; report:any }>();
const money = (cents:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((cents||0)/100);
const date = (value:string|null) => value ? new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '—';
</script>
<template>
<Head :title="`Operations: ${report.order.order_number}`" />
<div class="analytics-report-page space-y-8 p-6">
<AnalyticsHeader :title="report.order.order_number" description="Order payment, fulfillment, financial, and status-transition details."><template #actions><Button variant="outline" as-child><a :href="`/admin/orders/${report.order.id}`">Manage order</a></Button></template></AnalyticsHeader>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Order total" :value="money(report.order.total_cents)"><template #icon><BadgeDollarSign class="h-5 w-5"/></template></MetricCard><MetricCard label="Payment status" :value="report.order.status.replaceAll('_',' ')"><template #icon><PackageCheck class="h-5 w-5"/></template></MetricCard><MetricCard label="Fulfillment" :value="report.order.fulfillment_status.replaceAll('_',' ')"><template #icon><PackageCheck class="h-5 w-5"/></template></MetricCard><MetricCard label="Fulfillment time" :value="report.performance?.fulfillment_hours == null ? '—' : `${report.performance.fulfillment_hours} hrs`"><template #icon><Clock3 class="h-5 w-5"/></template></MetricCard><MetricCard label="Needs attention" :value="report.performance?.needs_attention ? 'Yes' : 'No'"><template #icon><AlertTriangle class="h-5 w-5"/></template></MetricCard></section>
<div class="grid gap-6 xl:grid-cols-2"><ShowSection title="Order details"><dl class="grid gap-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Customer</dt><dd>{{report.order.customer_email||'Guest'}}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Provider</dt><dd class="capitalize">{{report.order.payment_provider||'—'}}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Paid</dt><dd>{{date(report.order.paid_at)}}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Shipped</dt><dd>{{date(report.order.shipped_at)}}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Delivered</dt><dd>{{date(report.order.delivered_at)}}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Fulfilled</dt><dd>{{date(report.order.fulfilled_at)}}</dd></div><div class="flex justify-between gap-4"><dt class="text-muted-foreground">Tracking</dt><dd>{{report.order.shipping_carrier||'—'}} {{report.order.tracking_number||''}}</dd></div></dl></ShowSection><ShowSection title="Items"><div v-for="item in report.items" :key="item.id" class="border-b py-3 last:border-b-0"><div class="font-medium">{{item.title}}</div><div class="text-sm text-muted-foreground">{{item.license_name||'License'}} · Qty {{item.quantity}} · {{money(item.total_price_cents)}}</div></div><AnalyticsEmptyState v-if="!report.items.length" title="No order items" description="No item records are attached to this order."/></ShowSection></div>
<div class="grid gap-6 xl:grid-cols-2"><ShowSection title="Fulfillment history"><div v-for="event in report.fulfillment_events" :key="`${event.status}-${event.created_at}`" class="border-b py-3 last:border-b-0"><div class="flex justify-between gap-3"><span class="font-medium capitalize">{{event.status.replaceAll('_',' ')}}</span><span class="text-xs text-muted-foreground">{{date(event.created_at)}}</span></div><div class="text-sm text-muted-foreground">{{event.note||'Status updated'}}<span v-if="event.actor"> · {{event.actor}}</span></div></div><AnalyticsEmptyState v-if="!report.fulfillment_events.length" title="No fulfillment history" description="No fulfillment status events have been recorded."/></ShowSection><ShowSection title="Financial transactions"><div v-for="tx in report.financial_transactions" :key="`${tx.type}-${tx.occurred_at}`" class="flex justify-between border-b py-3 last:border-b-0"><div><div class="font-medium capitalize">{{tx.type.replaceAll('_',' ')}}</div><div class="text-sm text-muted-foreground">{{tx.provider||'—'}} · {{date(tx.occurred_at)}}</div></div><div class="font-medium">{{money(tx.amount_cents)}}</div></div><AnalyticsEmptyState v-if="!report.financial_transactions.length" title="No financial transactions" description="No ledger entries are attached to this order."/></ShowSection></div>
</div></template>
