<?php
namespace Tests\Feature\Advertising;
use App\Models\{Advertiser,AdvertisingCampaign,AdvertisingInvoice,Permission,User}; use App\Services\AdvertisingBillingService; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Str; use Tests\TestCase;
class AdvertisingBillingTest extends TestCase {use RefreshDatabase;
 public function test_admin_can_create_issue_and_record_payment_for_advertising_invoice(): void {
  $user=User::factory()->create(['email_verified_at'=>now()]); foreach(['view_admin','view_advertising_billing','manage_advertising_invoices','record_advertising_payments','refund_advertising_payments'] as $name){$permission=Permission::query()->create(['name'=>$name,'label'=>Str::headline($name),'group_name'=>'Advertising','description'=>$name]);$user->permissions()->attach($permission);} $advertiser=Advertiser::query()->create(['uuid'=>(string)Str::uuid(),'name'=>'Example Sponsor','slug'=>'example-sponsor','status'=>'active','billing_email'=>'billing@example.test']); $campaign=AdvertisingCampaign::query()->create(['uuid'=>(string)Str::uuid(),'advertiser_id'=>$advertiser->id,'name'=>'Summer Sponsor','public_code'=>'AD-TEST-001','status'=>'approved','objective'=>'sponsorship','pricing_model'=>'sponsorship','budget_cents'=>50000,'contract_value_cents'=>50000]);
  $this->actingAs($user)->post('/admin/advertising-invoices',['advertiser_id'=>$advertiser->id,'advertising_campaign_id'=>$campaign->id,'currency'=>'USD','discount_cents'=>0,'tax_cents'=>0,'due_at'=>now()->addDays(30)->toDateString(),'items'=>[['description'=>'Summer sponsorship','billing_model'=>'sponsorship','quantity'=>1,'unit_amount_cents'=>50000]]])->assertRedirect();
  $invoice=AdvertisingInvoice::firstOrFail(); $this->assertSame(50000,$invoice->total_cents); $this->actingAs($user)->post('/admin/advertising-invoices/'.$invoice->id.'/issue')->assertRedirect(); $this->actingAs($user)->post('/admin/advertising-invoices/'.$invoice->id.'/payments',['amount_cents'=>20000,'provider'=>'manual'])->assertRedirect(); $invoice->refresh(); $this->assertSame('partially_paid',$invoice->status); $this->assertSame(30000,$invoice->balance_cents); $this->assertDatabaseHas('financial_transactions',['advertising_invoice_id'=>$invoice->id,'amount_cents'=>20000]); $this->actingAs($user)->get('/admin/advertising-invoices/'.$invoice->id)->assertOk()->assertInertia(fn($page)=>$page->component('Admin/Advertising/Billing/Show')->where('invoice.balance_cents',30000));
 }
}
