<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import DetailRow from '@/components/Shared/DetailRow.vue';
import StatusBadge from '@/components/Shared/StatusBadge.vue';
import ShowPageHeader from '@/components/Show/ShowPageHeader.vue';
import ShowSection from '@/components/Show/ShowSection.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
const props=defineProps<{licenseRecord:any}>();
const form=useForm({status:props.licenseRecord.stored_status,reason:props.licenseRecord.status_reason??'',customer_message:'',expires_at:props.licenseRecord.expires_at??'',download_limit:props.licenseRecord.download_limit,reset_downloads:false});
const submit=()=>form.patch(`/admin/licenses/${props.licenseRecord.id}/lifecycle`,{preserveScroll:true});
</script>
<template><Head :title="licenseRecord.license_key"/><div class="space-y-6"><ShowPageHeader title="License" :description="licenseRecord.license_key"><template #actions><StatusBadge :status="licenseRecord.status.key" :label="licenseRecord.status.label"/><Button variant="outline" as-child><Link href="/admin/licenses">Back to Licenses</Link></Button></template></ShowPageHeader>
<div class="grid gap-6 lg:grid-cols-3"><ShowSection title="License Summary"><div class="space-y-4"><DetailRow label="License" :value="licenseRecord.license_name"/><DetailRow label="Customer" :value="licenseRecord.user?.name"/><DetailRow label="Email" :value="licenseRecord.user?.email"/><DetailRow label="Asset" :value="licenseRecord.product?.title"/><DetailRow label="Order" :value="licenseRecord.order?.order_number"/><DetailRow label="Downloads" :value="`${licenseRecord.downloads_used} / ${licenseRecord.download_limit??'Unlimited'}`"/><DetailRow label="Starts" :value="licenseRecord.starts_at"/><DetailRow label="Expires" :value="licenseRecord.expires_at||'Never'"/></div></ShowSection>
<ShowSection title="Lifecycle Controls" description="Changes are audited and shown to the customer." class="lg:col-span-2"><form class="grid gap-4 sm:grid-cols-2" @submit.prevent="submit"><div class="space-y-2"><Label for="status">Status</Label><select id="status" v-model="form.status" class="h-10 w-full rounded-md border bg-background px-3"><option value="active">Active</option><option value="expired">Expired</option><option value="revoked">Revoked</option><option value="refunded">Refunded</option></select></div><div class="space-y-2"><Label for="expires_at">Expiration date</Label><Input id="expires_at" v-model="form.expires_at" type="date"/></div><div class="space-y-2"><Label for="download_limit">Download limit</Label><Input id="download_limit" v-model="form.download_limit" type="number" min="0"/></div><label class="flex items-center gap-2 self-end pb-2"><input v-model="form.reset_downloads" type="checkbox"/> Reset downloads used to zero</label><div class="space-y-2 sm:col-span-2"><Label for="reason">Internal reason</Label><Textarea id="reason" v-model="form.reason"/></div><div class="space-y-2 sm:col-span-2"><Label for="customer_message">Customer-facing message</Label><Textarea id="customer_message" v-model="form.customer_message"/></div><div class="sm:col-span-2"><Button :disabled="form.processing">Save Lifecycle Changes</Button></div></form></ShowSection></div>
<ShowSection title="Download History"><div v-if="licenseRecord.downloads.length" class="divide-y rounded-lg border"><div v-for="item in licenseRecord.downloads" :key="item.id" class="grid gap-1 p-4 sm:grid-cols-[1fr_auto]"><div><p class="font-medium">{{item.filename||item.download_type}}</p><p class="text-xs text-muted-foreground">{{item.status}} · {{item.ip_address||'No IP'}}</p></div><span class="text-sm text-muted-foreground">{{item.downloaded_at}}</span></div></div><p v-else class="text-sm text-muted-foreground">No downloads recorded.</p></ShowSection>
<ShowSection title="Lifecycle History"><div v-if="licenseRecord.history.length" class="space-y-3"><div v-for="item in licenseRecord.history" :key="item.id" class="rounded-lg border p-4"><p class="font-medium capitalize">{{item.from_status||'Created'}} → {{item.to_status}}</p><p v-if="item.reason" class="mt-1 text-sm">{{item.reason}}</p><p v-if="item.customer_message" class="mt-1 text-sm text-muted-foreground">Customer: {{item.customer_message}}</p><p class="mt-2 text-xs text-muted-foreground">{{item.changed_at}} · {{item.changed_by||'System'}}</p></div></div><p v-else class="text-sm text-muted-foreground">No lifecycle changes recorded.</p></ShowSection>
</div></template>
