<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { computed, nextTick, onMounted, ref } from 'vue';
import { ArrowLeft, ImagePlus, Layers3, Plus, Save, Trash2, Type } from '@lucide/vue';
import { Button } from '@/components/ui/button';

type DesignObject={id:string;type:'text'|'image';x:number;y:number;width:number;height:number;rotation:number;text?:string;fontSize?:number;color?:string;src?:string};
interface Project {uuid:string;title:string;canvas_width:number;canvas_height:number;design_json:{version:number;objects:DesignObject[]};source_url:string|null;save_url:string;upload_url:string;uploads:{uuid:string;name:string;url:string}[]}
const props=defineProps<{project:Project;export_presets:{name:string;width:number;height:number}[]}>();
const title=ref(props.project.title); const objects=ref<DesignObject[]>(props.project.design_json.objects||[]); const selectedId=ref<string|null>(null); const saving=ref(false); const fileInput=ref<HTMLInputElement|null>(null);
const selected=computed(()=>objects.value.find(o=>o.id===selectedId.value)||null); const scale=computed(()=>Math.min(1,900/props.project.canvas_width,600/props.project.canvas_height));
const stageStyle=computed(()=>({width:`${props.project.canvas_width*scale.value}px`,height:`${props.project.canvas_height*scale.value}px`}));
function id(){return crypto.randomUUID();}
function addText(){const o:DesignObject={id:id(),type:'text',x:80,y:80,width:520,height:100,rotation:0,text:'Double-click to edit',fontSize:64,color:'#ffffff'};objects.value.push(o);selectedId.value=o.id;}
function select(o:DesignObject){selectedId.value=o.id;}
function removeSelected(){objects.value=objects.value.filter(o=>o.id!==selectedId.value);selectedId.value=null;}
function save(){saving.value=true;router.put(props.project.save_url,{title:title.value,canvas_width:props.project.canvas_width,canvas_height:props.project.canvas_height,design_json:{version:1,objects:objects.value}},{preserveScroll:true,onFinish:()=>saving.value=false});}
async function upload(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const form=new FormData();form.append('image',file);const token=document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';const response=await fetch(props.project.upload_url,{method:'POST',headers:{'X-CSRF-TOKEN':token,'Accept':'application/json'},body:form});if(!response.ok){alert('The image could not be uploaded.');return;}const data=await response.json();const o:DesignObject={id:id(),type:'image',x:100,y:100,width:400,height:300,rotation:0,src:data.url};objects.value.push(o);selectedId.value=o.id;(e.target as HTMLInputElement).value='';}
function move(o:DesignObject,e:PointerEvent){const startX=e.clientX,startY=e.clientY,ox=o.x,oy=o.y;const onMove=(ev:PointerEvent)=>{o.x=Math.max(0,ox+(ev.clientX-startX)/scale.value);o.y=Math.max(0,oy+(ev.clientY-startY)/scale.value)};const done=()=>{window.removeEventListener('pointermove',onMove);window.removeEventListener('pointerup',done)};window.addEventListener('pointermove',onMove);window.addEventListener('pointerup',done);}
</script>
<template><Head :title="title"/><div class="min-h-screen bg-stone-950 text-white">
<header class="flex flex-wrap items-center gap-3 border-b border-white/10 px-4 py-3"><Button variant="ghost" as-child><Link href="/account/designs"><ArrowLeft class="mr-2 h-4 w-4"/>My Designs</Link></Button><input v-model="title" class="min-w-60 flex-1 rounded-lg border border-white/10 bg-white/5 px-3 py-2 font-semibold"/><span class="text-xs text-stone-400">{{project.canvas_width}} × {{project.canvas_height}}</span><Button :disabled="saving" @click="save"><Save class="mr-2 h-4 w-4"/>{{saving?'Saving…':'Save'}}</Button></header>
<div class="grid min-h-[calc(100vh-65px)] lg:grid-cols-[240px_minmax(0,1fr)_280px]">
<aside class="border-r border-white/10 p-4"><h2 class="text-xs font-semibold uppercase tracking-widest text-stone-400">Add</h2><div class="mt-4 grid gap-2"><Button variant="secondary" class="justify-start" @click="addText"><Type class="mr-2 h-4 w-4"/>Add text</Button><Button variant="secondary" class="justify-start" @click="fileInput?.click()"><ImagePlus class="mr-2 h-4 w-4"/>Upload image</Button><input ref="fileInput" type="file" accept="image/png,image/jpeg,image/webp" class="hidden" @change="upload"/></div><p class="mt-6 text-xs leading-5 text-stone-400">Drag elements directly on the canvas. The source image remains locked as the background.</p></aside>
<main class="overflow-auto p-6"><div class="mx-auto flex min-h-full items-center justify-center"><div class="relative overflow-hidden bg-stone-800 shadow-2xl" :style="stageStyle" @click.self="selectedId=null"><img v-if="project.source_url" :src="project.source_url" alt="Licensed source" class="absolute inset-0 h-full w-full select-none object-cover" draggable="false"/>
<div v-for="o in objects" :key="o.id" class="absolute cursor-move select-none" :class="selectedId===o.id?'ring-2 ring-sky-400':''" :style="{left:`${o.x*scale}px`,top:`${o.y*scale}px`,width:`${o.width*scale}px`,height:`${o.height*scale}px`,transform:`rotate(${o.rotation}deg)`}" @pointerdown.stop="select(o);move(o,$event)">
<img v-if="o.type==='image'" :src="o.src" class="h-full w-full object-contain" draggable="false"/><div v-else class="flex h-full items-center whitespace-pre-wrap" :style="{fontSize:`${(o.fontSize||48)*scale}px`,color:o.color||'#fff'}">{{o.text}}</div></div></div></div></main>
<aside class="border-l border-white/10 p-4"><h2 class="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-stone-400"><Layers3 class="h-4 w-4"/>Properties</h2><div v-if="selected" class="mt-5 space-y-4"><template v-if="selected.type==='text'"><label class="block text-sm">Text<textarea v-model="selected.text" rows="4" class="mt-2 w-full rounded-lg border border-white/10 bg-white/5 p-2"/></label><label class="block text-sm">Font size<input v-model.number="selected.fontSize" type="number" min="8" max="400" class="mt-2 w-full rounded-lg border border-white/10 bg-white/5 p-2"/></label><label class="block text-sm">Color<input v-model="selected.color" type="color" class="mt-2 h-10 w-full rounded"/></label></template><label class="block text-sm">Width<input v-model.number="selected.width" type="number" min="20" class="mt-2 w-full rounded-lg border border-white/10 bg-white/5 p-2"/></label><label class="block text-sm">Height<input v-model.number="selected.height" type="number" min="20" class="mt-2 w-full rounded-lg border border-white/10 bg-white/5 p-2"/></label><label class="block text-sm">Rotation<input v-model.number="selected.rotation" type="range" min="-180" max="180" class="mt-2 w-full"/></label><Button variant="destructive" class="w-full" @click="removeSelected"><Trash2 class="mr-2 h-4 w-4"/>Remove element</Button></div><p v-else class="mt-5 text-sm text-stone-400">Select an element to edit it.</p>
<div class="mt-8 border-t border-white/10 pt-5"><h3 class="text-sm font-semibold">Export sizes</h3><p class="mt-2 text-xs text-stone-400">High-resolution rendering is the next implementation phase.</p><div class="mt-3 space-y-2"><div v-for="preset in export_presets" :key="preset.name" class="rounded-lg bg-white/5 p-3 text-xs"><strong>{{preset.name}}</strong><span class="float-right text-stone-400">{{preset.width}}×{{preset.height}}</span></div></div></div></aside>
</div></div></template>
