<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('sponsorship_packages', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('code')->unique();$t->text('description')->nullable();$t->unsignedInteger('duration_days')->default(30);$t->unsignedBigInteger('base_price_cents')->default(0);$t->unsignedBigInteger('package_price_cents')->default(0);$t->unsignedBigInteger('impression_goal')->nullable();$t->unsignedBigInteger('click_goal')->nullable();$t->unsignedInteger('included_creatives')->default(1);$t->string('billing_terms')->default('Due on receipt');$t->boolean('is_active')->default(true)->index();$t->text('internal_notes')->nullable();$t->timestamps();});
  Schema::create('sponsorship_package_placement', function(Blueprint $t){$t->id();$t->foreignId('sponsorship_package_id')->constrained()->cascadeOnDelete();$t->foreignId('ad_placement_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('quantity')->default(1);$t->unsignedInteger('priority')->default(50);$t->unique(['sponsorship_package_id','ad_placement_id'],'sponsor_package_placement_unique');});
  Schema::create('sponsorship_leads', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('advertiser_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->string('company_name');$t->string('contact_name')->nullable();$t->string('contact_email')->nullable();$t->string('contact_phone')->nullable();$t->string('source')->nullable();$t->string('stage')->default('new')->index();$t->unsignedBigInteger('estimated_value_cents')->default(0);$t->unsignedTinyInteger('probability')->default(10);$t->date('target_close_date')->nullable()->index();$t->date('next_follow_up_at')->nullable()->index();$t->text('notes')->nullable();$t->string('lost_reason')->nullable();$t->timestamp('won_at')->nullable();$t->timestamp('lost_at')->nullable();$t->timestamps();$t->index(['assigned_to','stage']);});
  Schema::create('sales_activities', function(Blueprint $t){$t->id();$t->foreignId('sponsorship_lead_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('type')->default('note');$t->string('subject');$t->text('details')->nullable();$t->timestamp('occurred_at')->useCurrent()->index();$t->date('follow_up_at')->nullable();$t->timestamps();});
  Schema::create('sponsorship_proposals', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('proposal_number')->unique();$t->foreignId('sponsorship_lead_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('advertiser_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('sponsorship_package_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->string('title');$t->string('status')->default('draft')->index();$t->date('starts_on');$t->date('ends_on');$t->date('expires_on')->nullable()->index();$t->string('currency',3)->default('USD');$t->unsignedBigInteger('subtotal_cents')->default(0);$t->unsignedBigInteger('discount_cents')->default(0);$t->unsignedBigInteger('tax_cents')->default(0);$t->unsignedBigInteger('total_cents')->default(0);$t->text('terms')->nullable();$t->text('notes')->nullable();$t->timestamp('sent_at')->nullable();$t->timestamp('accepted_at')->nullable();$t->timestamp('declined_at')->nullable();$t->foreignId('converted_campaign_id')->nullable()->constrained('advertising_campaigns')->nullOnDelete();$t->foreignId('converted_invoice_id')->nullable()->constrained('advertising_invoices')->nullOnDelete();$t->timestamp('converted_at')->nullable();$t->timestamps();});
  Schema::create('sponsorship_proposal_items', function(Blueprint $t){$t->id();$t->foreignId('sponsorship_proposal_id')->constrained()->cascadeOnDelete();$t->foreignId('ad_placement_id')->nullable()->constrained()->nullOnDelete();$t->string('description');$t->string('billing_model')->default('sponsorship');$t->unsignedInteger('quantity')->default(1);$t->unsignedBigInteger('unit_amount_cents')->default(0);$t->unsignedBigInteger('line_total_cents')->default(0);$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('ad_inventory_reservations', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('ad_placement_id')->constrained()->cascadeOnDelete();$t->foreignId('advertising_campaign_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('sponsorship_proposal_id')->nullable()->constrained()->nullOnDelete();$t->string('status')->default('hold')->index();$t->date('starts_on')->index();$t->date('ends_on')->index();$t->timestamp('hold_expires_at')->nullable()->index();$t->unsignedInteger('quantity')->default(1);$t->text('notes')->nullable();$t->timestamps();$t->index(['ad_placement_id','starts_on','ends_on'],'inventory_availability_idx');});
 }
 public function down(): void {Schema::dropIfExists('ad_inventory_reservations');Schema::dropIfExists('sponsorship_proposal_items');Schema::dropIfExists('sponsorship_proposals');Schema::dropIfExists('sales_activities');Schema::dropIfExists('sponsorship_leads');Schema::dropIfExists('sponsorship_package_placement');Schema::dropIfExists('sponsorship_packages');}
};
