<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { Printer, PackageCheck, Truck, MapPin } from '@lucide/vue';
import { reactive } from 'vue';
import PageHeader from '@/Components/Shared/PageHeader.vue';
import StatusBadge from '@/Components/Shared/StatusBadge.vue';
import { Button } from '@/components/ui/button';
import type { AdminOrderDetail, SelectOption } from '@/types/order';

const props = defineProps<{ order: AdminOrderDetail; fulfillmentStatuses: SelectOption[] }>();
const form = reactive({ fulfillment_status: props.order.fulfillment_status, shipping_carrier: props.order.shipping_carrier ?? '', tracking_number: props.order.tracking_number ?? '', fulfillment_notes: props.order.fulfillment_notes ?? '', event_note: '' });
function saveFulfillment(){ router.patch(`/admin/orders/${props.order.id}/fulfillment`, form, { preserveScroll:true }); }
function money(cents:number){ return new Intl.NumberFormat('en-US',{style:'currency',currency:props.order.currency||'USD'}).format(cents/100); }
</script>
<template>
<Head :title="`Order ${order.order_number}`" />
<div class="space-y-6 p-6">
<PageHeader :title="`Order ${order.order_number}`" description="Complete payment, product, shipping, and fulfillment details.">
<template #default><div class="flex flex-wrap gap-2"><StatusBadge :status="order.status"/><StatusBadge :status="order.fulfillment_status"/><Button variant="outline" as-child><a :href="`/admin/orders/${order.id}/invoice`" target="_blank"><Printer class="mr-2 h-4 w-4"/>Print Invoice</a></Button><Button variant="outline" as-child><Link href="/admin/orders">Back</Link></Button></div></template>
</PageHeader>
<div class="grid gap-6 lg:grid-cols-3">
<section class="rounded-xl border p-5"><h2 class="font-semibold">Customer</h2><p class="mt-3">{{ order.user?.name || 'No user' }}</p><p class="text-sm text-muted-foreground">{{ order.user?.email }}</p></section>
<section class="rounded-xl border p-5 lg:col-span-2"><h2 class="font-semibold">Order Summary</h2><div class="mt-4 grid gap-3 sm:grid-cols-4"><div><p class="text-xs text-muted-foreground">Created</p><p>{{ order.created_at }}</p></div><div><p class="text-xs text-muted-foreground">Paid</p><p>{{ order.paid_at || '—' }}</p></div><div><p class="text-xs text-muted-foreground">Provider</p><p>{{ order.payment_provider || '—' }}</p></div><div><p class="text-xs text-muted-foreground">Total</p><p class="text-xl font-semibold">{{ order.total_formatted }}</p></div></div></section>
</div>
<section class="rounded-xl border p-5"><div class="flex items-center gap-2"><PackageCheck class="h-5 w-5"/><h2 class="font-semibold">Fulfillment</h2></div><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="text-sm">Status<select v-model="form.fulfillment_status" class="mt-1 h-10 w-full rounded-md border bg-background px-3"><option v-for="s in fulfillmentStatuses" :key="s.value" :value="s.value">{{ s.label }}</option></select></label><label class="text-sm">Carrier<input v-model="form.shipping_carrier" class="mt-1 h-10 w-full rounded-md border bg-background px-3" placeholder="USPS, UPS, FedEx..."/></label><label class="text-sm">Tracking number<input v-model="form.tracking_number" class="mt-1 h-10 w-full rounded-md border bg-background px-3"/></label><label class="text-sm">Timeline note<input v-model="form.event_note" class="mt-1 h-10 w-full rounded-md border bg-background px-3" placeholder="Optional note"/></label></div><label class="mt-4 block text-sm">Admin fulfillment notes<textarea v-model="form.fulfillment_notes" rows="3" class="mt-1 w-full rounded-md border bg-background p-3"/></label><Button class="mt-4" @click="saveFulfillment">Update Fulfillment</Button></section>
<section class="rounded-xl border p-5"><h2 class="font-semibold">Order Items</h2><div class="mt-4 space-y-4"><article v-for="item in order.items" :key="item.id" class="rounded-xl border p-4"><div class="flex flex-wrap justify-between gap-3"><div><h3 class="font-semibold">{{ item.title }}</h3><p class="text-sm text-muted-foreground">{{ item.license_name }} · {{ item.fulfillment_type }}</p></div><div class="text-right"><p>{{ item.quantity }} × {{ item.unit_price_formatted }}</p><p class="font-semibold">{{ item.total_price_formatted }}</p></div></div><div v-if="item.configuration?.labels?.length" class="mt-4 grid gap-2 sm:grid-cols-2"><div v-for="label in item.configuration.labels" :key="label.group" class="rounded-lg bg-muted/50 p-3 text-sm"><span class="font-medium">{{ label.group }}:</span> {{ label.values.join(', ') }}</div></div><div v-if="item.shipping_address" class="mt-4 rounded-lg border p-3 text-sm"><div class="flex items-center gap-2 font-medium"><MapPin class="h-4 w-4"/>Shipping Address</div><p class="mt-2">{{ item.shipping_address.full_name }}</p><p>{{ item.shipping_address.address_line_1 }}</p><p v-if="item.shipping_address.address_line_2">{{ item.shipping_address.address_line_2 }}</p><p>{{ item.shipping_address.city }}, {{ item.shipping_address.region }} {{ item.shipping_address.postal_code }}</p><p>{{ item.shipping_address.country_code }}</p><p v-if="item.shipping_address.phone">{{ item.shipping_address.phone }}</p><p v-if="item.shipping_address.delivery_instructions" class="mt-2 text-muted-foreground">Instructions: {{ item.shipping_address.delivery_instructions }}</p></div><div v-if="item.included_files?.length" class="mt-4"><p class="text-sm font-medium">Included Files</p><div class="mt-2 flex flex-wrap gap-2"><span v-for="(file,index) in item.included_files" :key="index" class="rounded-full border px-3 py-1 text-xs">{{ file.original_filename || file.filename || file.extension || 'File' }}</span></div></div></article></div></section>
<section class="grid gap-6 lg:grid-cols-2"><div class="rounded-xl border p-5"><h2 class="font-semibold">Totals</h2><div class="mt-4 space-y-2 text-sm"><div class="flex justify-between"><span>Subtotal</span><span>{{ money(order.subtotal_cents) }}</span></div><div class="flex justify-between"><span>Discount</span><span>{{ money(order.discount_cents) }}</span></div><div class="flex justify-between"><span>Tax</span><span>{{ money(order.tax_cents) }}</span></div><div class="flex justify-between border-t pt-3 text-lg font-semibold"><span>Total</span><span>{{ money(order.total_cents) }}</span></div></div></div><div class="rounded-xl border p-5"><div class="flex items-center gap-2"><Truck class="h-5 w-5"/><h2 class="font-semibold">Fulfillment Timeline</h2></div><div class="mt-4 space-y-3"><div v-for="event in order.fulfillment_events" :key="event.id" class="border-l-2 pl-4"><p class="font-medium capitalize">{{ event.status.replaceAll('_',' ') }}</p><p class="text-xs text-muted-foreground">{{ event.created_at }}<span v-if="event.user"> · {{ event.user }}</span></p><p v-if="event.note" class="mt-1 text-sm">{{ event.note }}</p></div><p v-if="!order.fulfillment_events.length" class="text-sm text-muted-foreground">No fulfillment updates yet.</p></div></div></section>
</div>
</template>
