<!doctype html><html><head><meta charset="utf-8"><title>Invoice {{ $order->order_number }}</title>
<style>body{font-family:Arial,sans-serif;color:#222;margin:32px}.row{display:flex;justify-content:space-between;gap:24px}.muted{color:#666}.box{border:1px solid #ddd;border-radius:10px;padding:16px;margin-top:18px}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top}.right{text-align:right}.total{font-size:20px;font-weight:700}.no-print{margin-bottom:20px}@media print{.no-print{display:none}body{margin:0}}</style></head><body>
<button class="no-print" onclick="window.print()">Print Invoice</button>
<div class="row"><div><h1>Unclad Collection</h1><div class="muted">Invoice / Order {{ $order->order_number }}</div></div><div class="right"><strong>{{ strtoupper($order->status) }}</strong><br><span class="muted">{{ $order->created_at?->format('F j, Y') }}</span></div></div>
<div class="row box"><div><strong>Customer</strong><br>{{ $order->user?->name }}<br>{{ $order->user?->email }}</div><div><strong>Fulfillment</strong><br>{{ str($order->fulfillment_status?->value ?? $order->fulfillment_status)->replace('_',' ')->title() }}<br>@if($order->shipping_carrier){{ $order->shipping_carrier }} @endif @if($order->tracking_number){{ $order->tracking_number }}@endif</div></div>
<table><thead><tr><th>Item</th><th>Details</th><th>Qty</th><th class="right">Unit</th><th class="right">Total</th></tr></thead><tbody>
@foreach($order->items as $item)<tr><td><strong>{{ $item->asset_title ?: $item->image_title }}</strong><br><span class="muted">{{ $item->offering_name ?: $item->license_name }}</span></td><td>
@foreach(($item->configuration_snapshot['labels'] ?? []) as $label)<div><strong>{{ $label['group'] ?? '' }}:</strong> {{ implode(', ', $label['values'] ?? []) }}</div>@endforeach
@if($item->shipping_address_snapshot)<div style="margin-top:8px"><strong>Ship to:</strong><br>{{ $item->shipping_address_snapshot['full_name'] ?? '' }}<br>{{ $item->shipping_address_snapshot['address_line_1'] ?? '' }} @if($item->shipping_address_snapshot['address_line_2'] ?? null)<br>{{ $item->shipping_address_snapshot['address_line_2'] }}@endif<br>{{ $item->shipping_address_snapshot['city'] ?? '' }}, {{ $item->shipping_address_snapshot['region'] ?? '' }} {{ $item->shipping_address_snapshot['postal_code'] ?? '' }}<br>{{ $item->shipping_address_snapshot['country_code'] ?? '' }}</div>@endif
</td><td>{{ $item->quantity }}</td><td class="right">{{ $item->unit_price_formatted }}</td><td class="right">{{ $item->total_price_formatted }}</td></tr>@endforeach
</tbody></table>
<div class="box" style="margin-left:auto;max-width:360px"><div class="row"><span>Subtotal</span><span>{{ $order->subtotal_formatted }}</span></div><div class="row"><span>Discount</span><span>${{ number_format($order->discount_cents/100,2) }}</span></div><div class="row"><span>Tax</span><span>${{ number_format($order->tax_cents/100,2) }}</span></div><hr><div class="row total"><span>Total</span><span>{{ $order->total_formatted }}</span></div></div>
</body></html>
