<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { ArrowLeft, Eye, MessageCircle, ShoppingBag, Users } from '@lucide/vue';
import { reactive } from 'vue';
import MetricCard from '@/Components/Shared/MetricCard.vue';
import PageHeader from '@/Components/Shared/PageHeader.vue';
import ShowSection from '@/Components/Show/ShowSection.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
const props=defineProps<{filters:any;report:any}>(); const filters=reactive({...props.filters});
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const apply=()=>router.get(`/admin/analytics/blog/${props.report.post.slug}`,filters,{preserveState:true,replace:true});
</script>
<template><Head :title="`${report.post.title} Analytics`"/><div class="space-y-8 p-6"><PageHeader :title="report.post.title" description="Individual post readership, engagement, and associated marketplace activity."><template #actions><Button variant="outline" as-child><Link href="/admin/analytics/blog"><ArrowLeft class="mr-2 h-4 w-4"/>All content</Link></Button></template></PageHeader>
<form class="grid gap-4 rounded-xl border bg-background p-4 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end" @submit.prevent="apply"><div class="grid gap-2"><Label>Period</Label><select v-model="filters.period" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="7_days">Last 7 days</option><option value="30_days">Last 30 days</option><option value="90_days">Last 90 days</option><option value="year_to_date">Year to date</option><option value="custom">Custom</option></select></div><div class="grid gap-2"><Label>Start</Label><Input v-model="filters.start_date" type="date" :disabled="filters.period!=='custom'"/></div><div class="grid gap-2"><Label>End</Label><Input v-model="filters.end_date" type="date" :disabled="filters.period!=='custom'"/></div><Button>Apply</Button></form>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Views" :value="report.performance.views.toLocaleString()"><template #icon><Eye class="h-5 w-5"/></template></MetricCard><MetricCard label="Unique readers" :value="report.performance.unique_readers.toLocaleString()"><template #icon><Users class="h-5 w-5"/></template></MetricCard><MetricCard label="Approved comments" :value="report.performance.comments.toLocaleString()" :trend="`${report.performance.engagement_rate_percent}% engagement`"><template #icon><MessageCircle class="h-5 w-5"/></template></MetricCard><MetricCard label="Influenced revenue" :value="money(report.performance.influenced_revenue_cents)" :trend="`${report.performance.influenced_orders} orders`"><template #icon><ShoppingBag class="h-5 w-5"/></template></MetricCard></section>
<ShowSection title="Daily readership" description="Views, readers, comments, and associated orders across the selected reporting period."><div class="overflow-x-auto rounded-lg border"><table class="w-full text-sm"><thead class="bg-muted/50 text-left"><tr><th class="p-3">Date</th><th class="p-3 text-right">Views</th><th class="p-3 text-right">Readers</th><th class="p-3 text-right">Comments</th><th class="p-3 text-right">Orders</th></tr></thead><tbody class="divide-y"><tr v-for="point in report.timeline" :key="point.date"><td class="p-3 font-medium">{{ point.label }}</td><td class="p-3 text-right">{{ point.views }}</td><td class="p-3 text-right">{{ point.unique_readers }}</td><td class="p-3 text-right">{{ point.comments }}</td><td class="p-3 text-right">{{ point.orders }}</td></tr></tbody></table></div></ShowSection>
<div class="grid gap-6 xl:grid-cols-2"><ShowSection title="Content details"><dl class="grid gap-3"><div><dt class="text-sm text-muted-foreground">Author</dt><dd class="font-medium">{{ report.post.author || 'Unknown' }}</dd></div><div><dt class="text-sm text-muted-foreground">Published</dt><dd class="font-medium">{{ report.post.published_at || '—' }}</dd></div><div><dt class="text-sm text-muted-foreground">Categories</dt><dd class="font-medium">{{ report.categories.map((c:any)=>c.name).join(', ') || 'Uncategorized' }}</dd></div><div><dt class="text-sm text-muted-foreground">Tags</dt><dd class="font-medium">{{ report.tags.map((t:any)=>t.name).join(', ') || 'No tags' }}</dd></div></dl></ShowSection><ShowSection title="Marketplace influence" description="Purchases by registered users who also viewed this post during the selected period."><div class="grid gap-3 sm:grid-cols-2"><div class="rounded-lg border p-4"><p class="text-sm text-muted-foreground">Associated buyers</p><p class="mt-1 text-2xl font-semibold">{{ report.performance.influenced_buyers }}</p></div><div class="rounded-lg border p-4"><p class="text-sm text-muted-foreground">Marketplace actions</p><p class="mt-1 text-2xl font-semibold">{{ report.performance.marketplace_actions }}</p></div></div></ShowSection></div>
</div></template>
