<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { BadgeDollarSign, Search, Users, AlertTriangle, ShoppingCart } from '@lucide/vue';
import { reactive } from 'vue';
import AnalyticsFilterPanel from '@/components/Analytics/AnalyticsFilterPanel.vue';
import AnalyticsHeader from '@/components/Analytics/AnalyticsHeader.vue';
import MetricCard from '@/Components/Shared/MetricCard.vue';
import ShowSection from '@/Components/Show/ShowSection.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
const props=defineProps<{filters:any;report:any}>(); const filters=reactive({...props.filters});
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const apply=()=>router.get('/admin/analytics/search',filters,{preserveState:true,replace:true});
const exportUrl=()=>'/admin/analytics/search/export?'+new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!=null) as [string,string][]).toString();
</script>
<template><Head title="Search and Discovery Analytics"/><div class="analytics-report-page space-y-8 p-6">
<AnalyticsHeader title="Search and Discovery Analytics" description="Understand what visitors look for, where inventory is weak, and which searches influence revenue."><template #actions><Button variant="outline" as-child><a :href="exportUrl()">Export CSV</a></Button></template></AnalyticsHeader>
<AnalyticsFilterPanel content-class="grid gap-4 lg:grid-cols-4 lg:items-end" @submit="apply"><div class="grid gap-2"><Label>Search terms</Label><Input v-model="filters.search" placeholder="Filter terms..."/></div><div class="grid gap-2"><Label>Result status</Label><select v-model="filters.result_status" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All searches</option><option value="zero">Zero results</option><option value="low">Low results</option></select></div><div class="grid gap-2"><Label>Period</Label><select v-model="filters.period" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="7_days">Last 7 days</option><option value="30_days">Last 30 days</option><option value="90_days">Last 90 days</option><option value="year_to_date">Year to date</option></select></div><Button type="submit">Apply filters</Button></AnalyticsFilterPanel>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Searches" :value="report.summary.searches"><template #icon><Search class="h-5 w-5"/></template></MetricCard><MetricCard label="Unique searchers" :value="report.summary.unique_searchers"><template #icon><Users class="h-5 w-5"/></template></MetricCard><MetricCard label="Zero results" :value="report.summary.zero_result_searches"><template #icon><AlertTriangle class="h-5 w-5"/></template></MetricCard><MetricCard label="Low results" :value="report.summary.low_result_searches"><template #icon><AlertTriangle class="h-5 w-5"/></template></MetricCard><MetricCard label="Influenced orders" :value="report.summary.influenced_orders"><template #icon><ShoppingCart class="h-5 w-5"/></template></MetricCard><MetricCard label="Influenced revenue" :value="money(report.summary.influenced_revenue_cents)"><template #icon><BadgeDollarSign class="h-5 w-5"/></template></MetricCard></section>
<ShowSection title="Search term performance" description="Ranked by influenced revenue and search demand."><div class="overflow-x-auto rounded-lg border"><table class="w-full text-sm"><thead class="bg-muted/40 text-left"><tr><th class="p-3">Term</th><th class="p-3">Searches</th><th class="p-3">Avg. results</th><th class="p-3">Zero</th><th class="p-3">Orders</th><th class="p-3">Revenue</th><th class="p-3">Conversion</th></tr></thead><tbody><tr v-for="row in report.terms" :key="row.term" class="border-t"><td class="p-3 font-medium"><Link :href="`/admin/analytics/search/${encodeURIComponent(row.term)}?period=${filters.period}`" class="hover:underline">{{row.term}}</Link></td><td class="p-3">{{row.searches}}</td><td class="p-3">{{row.average_results}}</td><td class="p-3">{{row.zero_result_searches}}</td><td class="p-3">{{row.influenced_orders}}</td><td class="p-3">{{money(row.influenced_revenue_cents)}}</td><td class="p-3">{{row.search_to_purchase_percent}}%</td></tr><tr v-if="!report.terms.length"><td colspan="7" class="p-10 text-center text-muted-foreground">No tracked searches in this period.</td></tr></tbody></table></div></ShowSection>
<div class="grid gap-6 xl:grid-cols-3"><ShowSection title="Catalog gaps"><div v-for="row in report.opportunities.catalog_gaps" :key="row.term" class="border-b py-3"><div class="font-medium">{{row.term}}</div><div class="text-sm text-muted-foreground">{{row.searches}} searches · {{row.average_results}} average results</div></div></ShowSection><ShowSection title="High demand, low conversion"><div v-for="row in report.opportunities.high_demand_low_conversion" :key="row.term" class="border-b py-3"><div class="font-medium">{{row.term}}</div><div class="text-sm text-muted-foreground">{{row.searches}} searches · {{row.search_to_purchase_percent}}% conversion</div></div></ShowSection><ShowSection title="Revenue drivers"><div v-for="row in report.opportunities.revenue_drivers" :key="row.term" class="border-b py-3"><div class="font-medium">{{row.term}}</div><div class="text-sm text-muted-foreground">{{money(row.influenced_revenue_cents)}} influenced revenue</div></div></ShowSection></div>
</div></template>
