<?php
namespace App\Http\Controllers\Admin;
use App\Enums\PageHelpAudience; use App\Http\Controllers\Controller; use App\Models\PageHelp; use App\Models\Permission; use App\Models\Role; use App\Services\PageHelp\PageHelpRegistry; use Illuminate\Http\Request; use Inertia\Inertia; use Inertia\Response;
class PageHelpController extends Controller {
 public function index(Request $r,PageHelpRegistry $registry):Response { $this->authorize('viewAny',PageHelp::class); $q=PageHelp::query()->withCount(['roles','permissions'])->with(['creator:id,name','updater:id,name']); if($s=trim((string)$r->input('search'))) $q->where(fn($x)=>$x->where('page_key','like',"%$s%")->orWhere('title','like',"%$s%")); if($a=$r->input('audience'))$q->where('audience',$a); if($r->filled('published'))$q->where('is_published',$r->boolean('published')); return Inertia::render('Admin/PageHelp/Index',['entries'=>$q->orderBy('page_key')->orderBy('sort_order')->paginate(25)->withQueryString(),'filters'=>$r->only(['search','audience','published']),'audiences'=>$this->audiences(),'registry'=>$registry->all()]); }
 public function create(Request $request, PageHelpRegistry $registry): Response { $this->authorize('create', PageHelp::class); $requestedKey = trim((string) $request->query('page_key', '')); $registeredKeys = collect($registry->all())->pluck('key'); $initialPageKey = $registeredKeys->contains($requestedKey) ? $requestedKey : ''; return Inertia::render('Admin/PageHelp/Form', $this->formData(null, $registry, $initialPageKey)); }
 public function store(Request $r){$this->authorize('create',PageHelp::class);$data=$this->validated($r);$data['created_by']=$r->user()->id;$data['updated_by']=$r->user()->id;$data=$this->publication($r,$data);$h=PageHelp::create($data);$h->roles()->sync($r->input('role_ids',[]));$h->permissions()->sync($r->input('permission_ids',[]));return redirect()->route('admin.page-help.edit',$h)->with('success','Page Help entry created.');}
 public function edit(PageHelp $pageHelp,PageHelpRegistry $registry):Response{$this->authorize('update',$pageHelp);$pageHelp->load(['roles:id','permissions:id']);return Inertia::render('Admin/PageHelp/Form',$this->formData($pageHelp,$registry));}
 public function update(Request $r,PageHelp $pageHelp){$this->authorize('update',$pageHelp);$data=$this->validated($r);$data['updated_by']=$r->user()->id;$data=$this->publication($r,$data);$pageHelp->update($data);$pageHelp->roles()->sync($r->input('role_ids',[]));$pageHelp->permissions()->sync($r->input('permission_ids',[]));return back()->with('success','Page Help entry updated.');}
 public function destroy(PageHelp $pageHelp){$this->authorize('delete',$pageHelp);$pageHelp->delete();return redirect()->route('admin.page-help.index')->with('success','Page Help entry deleted.');}
 public function coverage(PageHelpRegistry $registry):Response{$this->authorize('viewAny',PageHelp::class);$counts=PageHelp::query()->selectRaw('page_key,count(*) total,sum(is_published = 1 and is_active = 1) published')->groupBy('page_key')->get()->keyBy('page_key');$rows=collect($registry->all())->map(function($p)use($counts){$c=$counts->get($p['key']);return array_merge($p,['total'=>(int)($c->total??0),'published'=>(int)($c->published??0)]);})->values();return Inertia::render('Admin/PageHelp/Coverage',['rows'=>$rows]);}
 private function validated(Request $r):array{return $r->validate(['page_key'=>['required','string','max:160'],'title'=>['required','string','max:255'],'summary'=>['nullable','string','max:2000'],'content'=>['required','string'],'audience'=>['required','in:'.implode(',',PageHelpAudience::values())],'is_active'=>['required','boolean'],'is_published'=>['required','boolean'],'published_at'=>['nullable','date'],'sort_order'=>['required','integer','min:0'],'role_ids'=>['array'],'role_ids.*'=>['integer','exists:roles,id'],'permission_ids'=>['array'],'permission_ids.*'=>['integer','exists:permissions,id']]);}
 private function publication(Request $r,array $d):array{if($d['is_published']){$this->authorize('publish',new PageHelp);$d['published_at']=$d['published_at']?:now();}else{$d['published_at']=null;}return $d;}
 private function formData(?PageHelp $h, PageHelpRegistry $registry, string $initialPageKey = ''): array { return ['entry' => $h, 'initial_page_key' => $initialPageKey, 'registry' => $registry->all(), 'audiences' => $this->audiences(), 'roles' => Role::orderBy('label')->get(['id','name','label']), 'permissions' => Permission::orderBy('group_name')->orderBy('label')->get(['id','name','label','group_name'])]; }
 private function audiences():array{return collect(PageHelpAudience::cases())->map(fn($x)=>['value'=>$x->value,'label'=>$x->label()])->all();}
}
