<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\{AdPlacement, Advertiser, SponsorshipLead, SponsorshipPackage, SponsorshipProposal};
use App\Services\SponsorshipProposalConversionService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Inertia\Inertia;

class SponsorshipProposalController extends Controller
{
    public function index() { return Inertia::render('Admin/Sponsorship/Proposals/Index', ['proposals' => SponsorshipProposal::with(['advertiser','lead','package'])->latest()->get()]); }
    public function create(Request $request) { $package=$request->filled('package')?SponsorshipPackage::with('placements')->find($request->integer('package')):null; return Inertia::render('Admin/Sponsorship/Proposals/Form',['proposal'=>null,'selectedPackage'=>$package,'packages'=>SponsorshipPackage::where('is_active',true)->orderBy('name')->get(),'leads'=>SponsorshipLead::whereNotIn('stage',['lost','won'])->orderBy('company_name')->get(),'advertisers'=>Advertiser::orderBy('name')->get(),'placements'=>AdPlacement::where('is_active',true)->orderBy('name')->get()]); }
    public function store(Request $request) { $data=$this->data($request); $proposal=SponsorshipProposal::create(array_merge($data,['uuid'=>(string)Str::uuid(),'proposal_number'=>'SP-'.now()->format('Ymd').'-'.Str::upper(Str::random(5)),'created_by'=>$request->user()->id,'status'=>'draft'])); $this->replaceItems($proposal,$request); $this->history($request,$proposal,null,'draft','Proposal created.'); return to_route('admin.sponsorship-proposals.show',$proposal); }
    public function show(SponsorshipProposal $sponsorshipProposal) { return Inertia::render('Admin/Sponsorship/Proposals/Show',['proposal'=>$sponsorshipProposal->load(['advertiser','lead','package','items.placement','campaign','invoice','acceptance.user','statusHistory.user'])]); }
    public function edit(SponsorshipProposal $sponsorshipProposal) { abort_if(in_array($sponsorshipProposal->status,['accepted','converted']),422); return Inertia::render('Admin/Sponsorship/Proposals/Form',['proposal'=>$sponsorshipProposal->load('items'),'selectedPackage'=>null,'packages'=>SponsorshipPackage::where('is_active',true)->orderBy('name')->get(),'leads'=>SponsorshipLead::orderBy('company_name')->get(),'advertisers'=>Advertiser::orderBy('name')->get(),'placements'=>AdPlacement::where('is_active',true)->orderBy('name')->get()]); }
    public function update(Request $request,SponsorshipProposal $sponsorshipProposal) { abort_if(in_array($sponsorshipProposal->status,['accepted','converted']),422); $sponsorshipProposal->update($this->data($request)); $this->replaceItems($sponsorshipProposal,$request); return to_route('admin.sponsorship-proposals.show',$sponsorshipProposal); }
    public function status(Request $request,SponsorshipProposal $sponsorshipProposal) { $data=$request->validate(['status'=>'required|in:sent,accepted,declined,draft','reason'=>'nullable|string|max:2000']); $from=$sponsorshipProposal->status; $status=$data['status']; $updates=['status'=>$status]; if($status==='sent')$updates['sent_at']=now(); if($status==='accepted')$updates['accepted_at']=now(); if($status==='declined')$updates['declined_at']=now(); $sponsorshipProposal->update($updates); $this->history($request,$sponsorshipProposal,$from,$status,$data['reason']??null); return back()->with('success','Proposal status updated.'); }
    public function convert(Request $request,SponsorshipProposal $sponsorshipProposal,SponsorshipProposalConversionService $service) { $from=$sponsorshipProposal->status; $result=$service->convert($sponsorshipProposal); $sponsorshipProposal->refresh(); $this->history($request,$sponsorshipProposal,$from,'converted','Converted to advertising campaign and invoice.'); return to_route('admin.ad-campaigns.show',$result['campaign'])->with('success','Proposal converted to campaign and invoice.'); }
    private function history(Request $request,SponsorshipProposal $proposal,?string $from,string $to,?string $reason):void { $proposal->statusHistory()->create(['user_id'=>$request->user()?->id,'from_status'=>$from,'to_status'=>$to,'reason'=>$reason,'source'=>'admin','ip_address'=>$request->ip(),'user_agent'=>$request->userAgent()]); }
    private function data(Request $request):array { return $request->validate(['sponsorship_lead_id'=>'nullable|exists:sponsorship_leads,id','advertiser_id'=>'required|exists:advertisers,id','sponsorship_package_id'=>'nullable|exists:sponsorship_packages,id','title'=>'required|string|max:255','starts_on'=>'required|date','ends_on'=>'required|date|after_or_equal:starts_on','expires_on'=>'nullable|date','currency'=>'required|string|size:3','discount_cents'=>'required|integer|min:0','tax_cents'=>'required|integer|min:0','terms'=>'nullable|string','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.description'=>'required|string|max:255','items.*.ad_placement_id'=>'nullable|exists:ad_placements,id','items.*.billing_model'=>'required|in:flat,cpm,cpc,sponsorship','items.*.quantity'=>'required|integer|min:1','items.*.unit_amount_cents'=>'required|integer|min:0']); }
    private function replaceItems(SponsorshipProposal $proposal,Request $request):void { $proposal->items()->delete(); $subtotal=0; foreach($request->input('items',[]) as $item){$item['line_total_cents']=(int)$item['quantity']*(int)$item['unit_amount_cents'];$subtotal+=$item['line_total_cents'];$proposal->items()->create($item);} $proposal->update(['subtotal_cents'=>$subtotal,'total_cents'=>max(0,$subtotal-(int)$proposal->discount_cents+(int)$proposal->tax_cents)]); }
}
